version: '3.8'

services:
  # MongoDB service
  ecommerce_db:
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - ./server/mongo-volume:/data/db
    networks:
      - ecommerce-backend

  #Mongo seed
  mongo_seed:
    container_name: mongo_seed
    build: ./mongo-seed
    networks:
      - ecommerce-backend
    depends_on:
      - ecommerce_db

  # Node API service
  ecommerce_api:
    container_name: ecommerce_api
    restart: always
    build: ./server
    ports:
      - 3000:3002
    environment:
      - PORT=3002
      - DB_URI=mongodb://ecommerce_db:27017/
      - DB_URI_DOCKER=mongodb://ecommerce_db:27017/
      - DB_NAME=ecommerce
      - JWT_SECRET=secret-token

    depends_on:
      - ecommerce_db
    networks:
      - ecommerce-backend

  # Frontend App
  react_app:
    container_name: react-app
    build: ./client
    depends_on:
      - ecommerce_db
    ports:
      - 5000:5173
    stdin_open: true
    tty: true

volumes:
  mongo-volume:
    driver: local

networks:
  ecommerce-backend:
    driver: bridge
